### ISSUE TITLE
Support XDG Base Directory Specification

### ISSUE THREAD

**Issue by erikw** [benvan/sandboxd#11]
First of all, thanks for this really great shell plugin. I really like it!

# Background
Lately the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) has been gaining quite a steady [popularity](https://wiki.archlinux.org/title/XDG_Base_Directory#Support), even though it's been around for a long time already. The basic idea is to standardize where programs put their files e.g. all config files in a certain directory. The benefits for end users are many, including:

* No polluted $HOME/
* Can easily grep for only config files in `$XDG_CONFIG_HOME`
* Can decide where to store configurations in more complex setups (multi system setup e.g.)
* Easily wipe state by removing `$XDG_STATE_HOME` or even `$XDG_DATA_HOME`, but without destorying and configuration files.

The first point is maybe what most end users enjoy the most though.

# How
Specifically for this project, this should mean that the search for the configuration file should be done like:

1. If `$SANDBOXRC` is set, use this. This has the highest precedence.
1. **new** elseIf `$XDG_CONFIG_HOME` is *set*, look for `$XDG_CONFIG_HOME/sandboxd/sandboxrc`
1. **new**elseif If `$XDG_CONFIG_HOME` is *unset*, use the default value for the envvar which is `$HOME/.config`. Thus, the config file to look for is at `$HOME/.config/sandboxd/sandboxrc`
1. else fall-back to current legacy `$HOME/.sandboxrc`

The first two steps to can be codifed in bash like:
 `${XDG_CONFIG_HOME:-$HOME/.config}/sandboxd/sandboxrc`

**Comment by benvan** [comment]
Definitely in support of this 👍 . Sidenote, thank you for such a detailed and easy-to-understand issue!

Sounds like a very small change - if anyone's willing to take a crack at a PR, please do - otherwise I'll see if I can find some time in an upcoming weekend.

I'm not 100% sure how best to handle users who've either a) upgraded sandboxd to XDG support, or b) added XDG_CONFIG vars after using sandboxd. Perhaps the best thing is to fall through per dotfile - e.g:

1. If `$XDG_CONFIG_HOME/sandboxd/sandboxrc` exists, use it
2. Otherwise if `HOME/.config/sandboxd/sandboxrc` exists, use it

Alternative might be to simply emit a warning that both exist on startup

**Comment by erikw** [comment]
That could make sense as an upgrade path; prefer that given order above, but be nice and print a warning if both exist  (for a few releases at least) :)
